### ISSUE TITLE
Adding Parallel = true to query makes it only work for static functions.

### ISSUE THREAD

**Issue by emelrad12** [genaray/Arch#237]
Example this works

```
[Query(Parallel = false)]
private void SomeQuery(in Entity entity)
{
  this.somethng
}
```
but this doesnt
```
[Query(Parallel = true)]
private void SomeQuery(in Entity entity)
{
  this.somethng
}
```

This behavior should not happen just by switching the parallel options

**Comment by genaray** [comment]
Not released yet, will follow once Arch 1.3.0 is released :)

**Comment by genaray** [comment]
Should be fixed in the new source generator, if not please re open :)

**Comment by Houtamelo** [comment]
I've tried the new source generator and this wasn't fixed there.
